[package]
name = "scrabble-solver"
authors = ["Albert Robillard"]
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
docopt = "1.1.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
